# Generated by Django 2.2.8 on 2021-03-28 10:47

import Issues.helpers
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_department', models.CharField(max_length=100)),
                ('current_emplooyeId', models.CharField(max_length=100)),
                ('issue_title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('entity', models.CharField(max_length=30)),
                ('order_id', models.CharField(max_length=30)),
                ('product_id', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(1, 'ToDo'), (2, 'In Progress'), (3, 'Done')], default=1)),
                ('final_resolution', models.CharField(max_length=200)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_closed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IssueImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Issues.helpers.image_upload_to_product)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Issues.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplooye_id', models.CharField(max_length=30)),
                ('emplooye_comment', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(1, 'ToDo'), (2, 'In Progress'), (3, 'Done')], default=1)),
                ('department', models.CharField(max_length=100)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Issues.Issue')),
            ],
        ),
    ]
