# Generated by Django 2.2.8 on 2021-03-30 00:07

import Issues.helpers
import Issues.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplooye_id', models.CharField(max_length=30)),
                ('emplooye_comment', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.CharField(choices=[(1, 'Customer Care'), (2, 'Account Section'), (3, 'Finance')], max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='time_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='time_closed',
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='user_id',
            field=models.CharField(default=Issues.helpers.getUserId, max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='current_department',
            field=models.IntegerField(choices=[(1, 'Customer Care'), (2, 'Account Section'), (3, 'Finance')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='current_emplooyeId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='entity',
            field=models.CharField(blank=True, default='getEntityByProductId', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='final_resolution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='order_id',
            field=models.CharField(max_length=30, validators=[Issues.validators.checkOrderId]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='product_id',
            field=models.CharField(max_length=30, validators=[Issues.validators.checkProductId]),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='transfer',
            name='issue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Issues.Issue'),
        ),
    ]
