# Generated by Django 2.2.8 on 2021-04-24 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='current_department',
            field=models.CharField(choices=[('CUSTOMER_CARE', 'CUSTOMER_CARE'), ('FINANCE', 'FINANCE')], default='CUSTOMER_CARE', max_length=30),
        ),
        migrations.AlterField(
            model_name='issue',
            name='current_employeeId',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
