# Generated by Django 3.2.4 on 2021-11-27 09:26

import Issues.helpers
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0004_alter_issueimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Issues.helpers.image_upload_to_issue),
        ),
    ]
