# Generated by Django 3.2.4 on 2021-12-04 07:41

import Issues.helpers
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0005_alter_issueimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=Issues.helpers.image_upload_to_issue),
        ),
    ]
