# Generated by Django 3.2.4 on 2022-03-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0008_alter_issueimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='entity_type',
            field=models.CharField(default='Rental', max_length=100),
            preserve_default=False,
        ),
    ]
