# Generated by Django 3.2.4 on 2022-03-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0009_issue_entity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='status',
            new_name='support_status',
        ),
    ]
