# Generated by Django 3.2.4 on 2022-03-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0010_rename_status_issue_support_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='entity_type',
            field=models.CharField(choices=[('STAY', 'STAY'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('EVENT', 'EVENT')], max_length=30),
        ),
    ]
