from Bookings.exportapi import get_completed_booking_details_for_entity_ids


def get_completed_bookings_by_entity_id(entity_filters, entity_ids):
    return get_completed_booking_details_for_entity_ids(entity_filters, entity_ids)