# Generated by Django 2.2.8 on 2021-03-28 11:52

import Coupons.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=Coupons.helpers.get_random_code, max_length=15, verbose_name='User Id')),
                ('coupon', models.CharField(default=Coupons.helpers.get_random_code, max_length=15, verbose_name='Coupon Id')),
                ('order_id', models.CharField(default=Coupons.helpers.get_random_code, max_length=15, verbose_name='Order Id')),
                ('ordered_date', models.DateTimeField()),
                ('total_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default=Coupons.helpers.get_random_code, max_length=15, verbose_name='Product Id')),
                ('entity', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('quantity', models.IntegerField(max_length=5)),
                ('product_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Orders', verbose_name='Order Id')),
            ],
        ),
    ]
