# Generated by Django 2.2.8 on 2021-04-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='user',
            new_name='created_by',
        ),
    ]
