# Generated by Django 2.2.8 on 2021-03-28 14:15

import Bookings.validators
import Coupons.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='product',
            field=models.CharField(max_length=16, validators=[Bookings.validators.checkProductId], verbose_name='Product Id'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='coupon',
            field=models.CharField(max_length=16, validators=[Bookings.validators.checkCouponId], verbose_name='Coupon Id'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default=Coupons.helpers.get_random_code, max_length=16, verbose_name='Order Id'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.CharField(default=Bookings.validators.getUserId, max_length=16, verbose_name='User Id'),
        ),
    ]
