# Generated by Django 2.2.8 on 2021-04-18 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 20, 24, 28, 889637)),
        ),
        migrations.CreateModel(
            name='CheckOutDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out', models.DateTimeField(default=datetime.datetime(2021, 4, 18, 20, 24, 28, 893403))),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Bookings')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(default=datetime.datetime(2021, 4, 18, 20, 24, 28, 892406))),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Bookings')),
            ],
        ),
        migrations.CreateModel(
            name='CancelledDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancelled_time', models.DateTimeField(default=datetime.datetime(2021, 4, 18, 20, 24, 28, 893540))),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Bookings')),
            ],
        ),
    ]
