# Generated by Django 2.2.8 on 2021-06-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedProductExtraDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(blank=True, choices=[('ROUND', 'ROUND'), ('SINGLE', 'SINGLE')], max_length=30, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=36, null=True)),
                ('drop_location', models.CharField(blank=True, max_length=36, null=True)),
                ('km_limit', models.PositiveIntegerField()),
                ('km_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('excess_km_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('excess_duration_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('is_infinity', models.BooleanField(default=False)),
                ('single_trip_return_value_per_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('booked_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.BookedProducts')),
            ],
        ),
    ]
