# Generated by Django 2.2.8 on 2021-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedproducts',
            name='size',
            field=models.CharField(default=0, max_length=10, verbose_name='Size'),
            preserve_default=False,
        ),
    ]
