# Generated by Django 2.2.8 on 2021-04-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'ONGOING'), (3, 'CANCELLED'), (4, 'DONE')], default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (2, 'DONE')], default=1),
        ),
    ]
