# Generated by Django 2.2.8 on 2021-05-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='coupon',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Coupon Id'),
        ),
    ]
