# Generated by Django 3.2.4 on 2021-10-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeYourOwnTripDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_vehicle', models.CharField(max_length=36)),
                ('no_of_adults', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('no_of_vehicles', models.IntegerField()),
                ('min_budget', models.FloatField(default=0.0)),
                ('max_budget', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='transportbookingdetails',
            name='make_your_own_trip_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bookings.makeyourowntripdetails'),
        ),
    ]
