# Generated by Django 2.2.8 on 2021-04-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedproducts',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='businessclientreportoncustomer',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='cancelleddetails',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='checkindetails',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='checkoutdetails',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.AlterUniqueTogether(
            name='bookedproducts',
            unique_together={('booking', 'product_id')},
        ),
    ]
