# Generated by Django 2.2.8 on 2021-06-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbookingdetails',
            name='distance_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bookings.TransportBookingDistanceDetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportbookingdetails',
            name='duration_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bookings.TransportBookingDurationDetails'),
            preserve_default=False,
        ),
    ]
