# Generated by Django 2.2.8 on 2021-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCustomerResons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasons', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cancelleddetails',
            unique_together={('booking', 'booking')},
        ),
        migrations.AlterUniqueTogether(
            name='checkindetails',
            unique_together={('booking', 'booking')},
        ),
        migrations.AlterUniqueTogether(
            name='checkoutdetails',
            unique_together={('booking', 'booking')},
        ),
    ]
