# Generated by Django 3.2.4 on 2021-07-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bookedproducts',
            name='price_type',
            field=models.CharField(choices=[('DAY', 'DAY'), ('HOUR', 'HOUR'), ('MONTH', 'MONTH'), ('PACKAGE', 'PACKAGE')], default='DAY', max_length=30, verbose_name='Price Type'),
        ),
    ]
