# Generated by Django 2.2.8 on 2021-04-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedproducts',
            name='net_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
