# Generated by Django 2.2.8 on 2021-06-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_bookedproductextradetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookedProductExtraDetails',
            new_name='TransportBookingDetails',
        ),
    ]
