# Generated by Django 2.2.8 on 2021-04-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_auto_20210423_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckOutProductImages',
            new_name='CheckOutImages',
        ),
        migrations.RemoveField(
            model_name='checkoutdetails',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='checkoutdetails',
            name='review',
        ),
    ]
