# Generated by Django 2.2.8 on 2021-04-19 13:21

import Bookings.helpers
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_auto_20210418_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkindetails',
            name='caution_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='checkindetails',
            name='id_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=Bookings.helpers.image_upload_to_user_id_proof),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkindetails',
            name='id_proof_type',
            field=models.CharField(choices=[('AADHAR_CARD', 'AADHAR_CARD'), ('PAN_CARD', 'PAN_CARD'), ('VOTER_ID', 'VOTER_ID')], default='AADHAR_CARD', max_length=30),
        ),
        migrations.AddField(
            model_name='checkindetails',
            name='is_caution_deposit_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='cancelleddetails',
            name='cancelled_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='checkindetails',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='checkoutdetails',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='OtherImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_image_id', models.ImageField(upload_to=Bookings.helpers.image_upload_to_user_id_proof)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.CheckInDetails')),
            ],
        ),
    ]
