# Generated by Django 3.2.4 on 2021-09-26 06:32

import Bookings.helpers
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_auto_20210828_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkindetails',
            name='id_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Bookings.helpers.image_upload_to_user_id_proof),
        ),
        migrations.AlterField(
            model_name='checkinimages',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Bookings.helpers.image_upload_to_check_in),
        ),
        migrations.AlterField(
            model_name='checkoutimages',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Bookings.helpers.image_upload_to_check_out),
        ),
    ]
