# Generated by Django 2.2.8 on 2021-04-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_auto_20210425_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcustomerresons',
            old_name='reasons',
            new_name='reason',
        ),
    ]
