# Generated by Django 2.2.8 on 2021-05-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_auto_20210525_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='entity_type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('EVENT', 'EVENT')], max_length=30),
        ),
    ]
