# Generated by Django 2.2.8 on 2021-06-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_auto_20210629_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportbookingdistancedetails',
            old_name='is_kms_infinity',
            new_name='is_km_infinity',
        ),
    ]
