# Generated by Django 2.2.8 on 2021-05-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_auto_20210505_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentBooking',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='entity_type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('RESORT', 'RESORT'), ('EVENT', 'EVENT')], default='HOTEL', max_length=30),
        ),
    ]
