# Generated by Django 2.2.8 on 2021-05-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_auto_20210429_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='payment_mode',
            field=models.CharField(choices=[('COD', 'COD'), ('ONLINE', 'ONLINE')], default='ONLINE', max_length=30),
        ),
        migrations.AddField(
            model_name='bookings',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('DONE', 'DONE'), ('NOT_REQUIRED', 'NOT_REQUIRED')], default='PENDING', max_length=30),
        ),
    ]
