# Generated by Django 2.2.8 on 2021-04-24 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_auto_20210423_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 19, 17, 2, 645843)),
        ),
    ]
