# Generated by Django 2.2.8 on 2021-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_bookedproducts_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedproducts',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Size'),
        ),
    ]
