# Generated by Django 2.2.8 on 2021-05-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_auto_20210528_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedproducts',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
    ]
