# Generated by Django 2.2.8 on 2021-04-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_auto_20210425_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='payment_status',
        ),
    ]
