# Generated by Django 2.2.8 on 2021-05-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_auto_20210525_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='entity_type',
            field=models.CharField(choices=[('STAY', 'STAY'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('EVENT', 'EVENT')], max_length=30),
        ),
    ]
