# Generated by Django 2.2.8 on 2021-04-19 23:43

import Bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_auto_20210419_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='caution_deposit_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, max_length=5),
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='reason_for_deduction',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='review',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='checkoutdetails',
            name='id',
            field=models.CharField(default=Bookings.models.getId, max_length=36, primary_key=True, serialize=False),
        ),
    ]
