# Generated by Django 3.2.4 on 2021-10-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_alter_transportbookingdetails_distance_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessclientquotation',
            old_name='product',
            new_name='vehicle',
        ),
    ]
