# Generated by Django 2.2.8 on 2021-06-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_auto_20210620_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportbookingdetails',
            old_name='is_infinity',
            new_name='is_kms_infinity',
        ),
    ]
