# Generated by Django 2.2.8 on 2021-06-29 18:28

import Bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_auto_20210629_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='otp',
            field=models.IntegerField(default=Bookings.models.generate_otp),
        ),
    ]
