# Generated by Django 2.2.8 on 2021-04-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_auto_20210424_1917'),
        ('Bookings', '0003_auto_20210425_1750'),
    ]

    operations = [
    ]
