# Generated by Django 2.2.8 on 2021-04-24 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_auto_20210424_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 19, 38, 32, 543775)),
        ),
    ]
