# Generated by Django 2.2.8 on 2021-06-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_auto_20210620_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportbookingdetails',
            old_name='excess_duration_price',
            new_name='excess_day_duration_price',
        ),
        migrations.RenameField(
            model_name='transportbookingdetails',
            old_name='km_limit',
            new_name='km_day_limit',
        ),
        migrations.AddField(
            model_name='transportbookingdetails',
            name='excess_hour_duration_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transportbookingdetails',
            name='km_hour_limit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
