# Generated by Django 2.2.8 on 2021-06-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_bookings_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportbookingdistancedetails',
            old_name='is_km_infinity',
            new_name='is_infinity',
        ),
        migrations.RemoveField(
            model_name='businessclientproductcancellation',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='businessclientproductcancellation',
            name='time',
        ),
        migrations.AddField(
            model_name='cancelleddetails',
            name='reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportbookingdistancedetails',
            name='km_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportbookingdistancedetails',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
