# Generated by Django 2.2.8 on 2021-04-19 23:54

import Bookings.helpers
import Bookings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_auto_20210419_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedproducts',
            name='id',
            field=models.CharField(default=Bookings.models.getId, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cancelleddetails',
            name='id',
            field=models.CharField(default=Bookings.models.getId, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='checkindetails',
            name='id',
            field=models.CharField(default=Bookings.models.getId, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otherimages',
            name='id',
            field=models.CharField(default=Bookings.models.getId, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CheckOutProductImages',
            fields=[
                ('id', models.CharField(default=Bookings.models.getId, max_length=36, primary_key=True, serialize=False)),
                ('product_image_id', models.ImageField(upload_to=Bookings.helpers.image_upload_to_user_id_proof)),
                ('check_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.CheckOutDetails')),
            ],
        ),
    ]
