# Generated by Django 2.2.8 on 2021-03-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_auto_20210328_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=16, verbose_name='Booking Id')),
                ('product_id', models.CharField(max_length=16, verbose_name='Product Id')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('booking_id', 'product_id')},
            },
        ),
    ]
