# Generated by Django 2.2.8 on 2021-05-29 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_auto_20210528_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedproducts',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookedproducts',
            name='parent_booked_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bookings.BookedProducts', verbose_name='Parent Care Product Id'),
        ),
    ]
