# Generated by Django 3.2.4 on 2021-11-06 06:26

import Bookings.helpers
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_auto_20210928_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkindetails',
            name='id_image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=Bookings.helpers.image_upload_to_user_id_proof),
        ),
        migrations.AlterField(
            model_name='checkinimages',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=Bookings.helpers.image_upload_to_check_in),
        ),
        migrations.AlterField(
            model_name='checkoutimages',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=Bookings.helpers.image_upload_to_check_out),
        ),
    ]
