# Generated by Django 2.2.8 on 2021-03-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_rentbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproducts',
            old_name='order_id',
            new_name='booking_id',
        ),
        migrations.RenameField(
            model_name='orderedproducts',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='orderedproducts',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='orderedproducts',
            old_name='start_date',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='ordered_date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_id',
            new_name='booking_id',
        ),
        migrations.AddField(
            model_name='orderedproducts',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='entity_type',
            field=models.IntegerField(choices=[(1, 'Hotels'), (2, 'Transport'), (3, 'Rentals'), (4, 'Resorts'), (5, 'Events')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='orderedproducts',
            unique_together={('booking_id', 'product_id')},
        ),
    ]
