# Generated by Django 2.2.8 on 2021-04-20 16:18

import Bookings.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_auto_20210419_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.CharField(default=Bookings.models.getId, max_length=36, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=50)),
                ('utr', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('UPI', 'UPI'), ('COD', 'COD'), ('CARD', 'CARD')], default='UPI', max_length=10)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime.now)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Bookings')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessClientReportOnCustomer',
            fields=[
                ('id', models.CharField(default=Bookings.models.getId, max_length=36, primary_key=True, serialize=False)),
                ('reasons_selected', models.CharField(max_length=100)),
                ('additional_info', models.CharField(max_length=10000)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Bookings')),
            ],
        ),
    ]
