# Generated by Django 2.2.8 on 2021-06-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_auto_20210622_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbookingdetails',
            name='booking_ending_vehicle_km_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transportbookingdetails',
            name='booking_starting_vehicle_km_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transportbookingdetails',
            name='km_day_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transportbookingdetails',
            name='km_hour_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
