# Generated by Django 2.2.8 on 2021-06-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_auto_20210622_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportbookingdetails',
            old_name='km_price',
            new_name='km_day_price',
        ),
        migrations.AddField(
            model_name='transportbookingdetails',
            name='km_hour_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
