# Generated by Django 3.2.4 on 2021-11-09 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_rename_product_businessclientquotation_vehicle'),
        ('Bookings', '0006_auto_20211106_1156'),
    ]

    operations = [
    ]
