# Generated by Django 2.2.8 on 2021-06-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0007_auto_20210601_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedproducts',
            name='parent_booked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bookings.BookedProducts', verbose_name='Parent Booked Product Id'),
        ),
        migrations.AlterUniqueTogether(
            name='bookedproducts',
            unique_together={('booking', 'product_id', 'hidden', 'parent_booked_product')},
        ),
    ]
