# Generated by Django 2.2.8 on 2021-06-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_auto_20210525_2217'),
        ('Bookings', '0008_auto_20210602_1748'),
    ]

    operations = [
    ]
