# Generated by Django 3.2.4 on 2021-11-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0007_merge_20211109_0836'),
        ('Bookings', '0008_eventsdetails_eventsprices'),
    ]

    operations = [
    ]
