# Generated by Django 2.2.8 on 2021-06-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0009_merge_20210604_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_status',
            field=models.CharField(choices=[('YET_TO_APPROVE', 'YET_TO_APPROVE'), ('BUSINESS_CLIENT_REJECTED', 'BUSINESS_CLIENT_REJECTED'), ('BUSINESS_CLIENT_NOT_ACTED', 'BUSINESS_CLIENT_NOT_ACTED'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('CANCELLED', 'CANCELLED'), ('DONE', 'DONE')], default='YET_TO_APPROVE', max_length=30),
        ),
    ]
