# Generated by Django 2.2.8 on 2021-06-08 20:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0009_merge_20210604_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClientQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_id', models.CharField(max_length=36)),
                ('vehicle_name', models.CharField(max_length=40)),
                ('amount', models.IntegerField()),
                ('booking_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=36)),
            ],
        ),
    ]
