# Generated by Django 2.2.8 on 2021-06-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0009_merge_20210604_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedproducts',
            name='has_sub_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='entity_type',
            field=models.CharField(choices=[('STAY', 'STAY'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('EVENT', 'EVENT'), ('HIRE_A_VEHICLE', 'HIRE_A_VEHICLE')], max_length=30),
        ),
    ]
