# Generated by Django 2.2.8 on 2021-06-09 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0010_businessclientquotation_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='quotation',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='Bookings.Quotation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessclientquotation',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='businessclientquotation',
            unique_together={('bc_id', 'booking_id')},
        ),
    ]
