# Generated by Django 2.2.8 on 2021-06-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0010_auto_20210612_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('PARTIAL', 'PARTIAL'), ('FULL', 'FULL')], max_length=30, null=True),
        ),
    ]
