# Generated by Django 2.2.8 on 2021-06-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0011_bookings_transaction_type'),
        ('Bookings', '0010_auto_20210613_1538'),
    ]

    operations = [
    ]
