# Generated by Django 2.2.8 on 2021-06-15 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0011_auto_20210609_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessclientquotation',
            old_name='bc_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='businessclientquotation',
            old_name='booking_id',
            new_name='entity_id',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='quotation',
        ),
        migrations.AddField(
            model_name='businessclientquotation',
            name='product',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessclientquotation',
            name='quotation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Bookings.Quotation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessclientquotation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='booking_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bookings.Bookings'),
        ),
        migrations.AlterUniqueTogether(
            name='businessclientquotation',
            unique_together={('created_by', 'quotation')},
        ),
        migrations.RemoveField(
            model_name='businessclientquotation',
            name='vehicle_name',
        ),
    ]
