# Generated by Django 2.2.8 on 2021-06-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0012_merge_20210615_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='entity_type',
            field=models.CharField(choices=[('STAY', 'STAY'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('EVENT', 'EVENT')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('PARTIAL', 'PARTIAL'), ('FULL', 'FULL')], max_length=30, null=True),
        ),
    ]
