# Generated by Django 2.2.8 on 2021-05-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggeditem',
            name='object_id',
            field=models.CharField(db_index=True, max_length=36, verbose_name='object ID'),
        ),
    ]
