# Generated by Django 3.2.4 on 2022-03-09 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Refer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferAndEarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_earned', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('EARNED', 'EARNED')], default='PENDING', max_length=20)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL, verbose_name='Referred By')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_user', to=settings.AUTH_USER_MODEL, verbose_name='Referred User')),
            ],
        ),
    ]
