# Generated by Django 2.2.8 on 2021-05-15 15:30

import Refer.validations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30)),
                ('client_name', models.CharField(max_length=30)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), Refer.validations.validate_phone])),
                ('stream', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('YET_TO_VERIFY', 'YET_TO_VERIFY'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='YET_TO_VERIFY', max_length=20)),
            ],
        ),
    ]
