# Generated by Django 3.2.4 on 2022-03-09 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refer', '0002_referandearn'),
    ]

    operations = [
        migrations.AddField(
            model_name='referandearn',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
