# Generated by Django 2.2.8 on 2021-04-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Refer', '0002_auto_20210423_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referbusinessclient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
