from .BaseProduct.admin import *
from .Category.admin import *
from .Hotel.admin import *
from .VehicleTypes.admin import *
from .Rental.admin import *
from .Vehicle.admin import *
from .HireAVehicle.admin import *
from .Driver.admin import *
from .Places.admin import *
from .TravelPackages.admin import *
