# Generated by Django 2.2.8 on 2021-05-05 21:47

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='trans_id',
            new_name='transaction_id',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
