# Generated by Django 3.2.4 on 2022-03-04 18:49

import Wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.CharField(default=Wallet.models.get_id, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='id',
            field=models.CharField(default=Wallet.models.get_id, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
