# Generated by Django 3.2.4 on 2022-03-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_auto_20220305_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='transaction_id',
            new_name='reward_related_id',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reward_type',
            field=models.CharField(choices=[('BOOKING', 'BOOKING'), ('REFER_AND_EARN', 'REFER_AND_EARN')], default='BOOKING', max_length=30),
        ),
    ]
