# Generated by Django 2.2.8 on 2021-05-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_auto_20210505_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
