# Generated by Django 3.2.4 on 2022-03-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_auto_20220311_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='reward_related_id',
            new_name='related_id',
        ),
    ]
