# Generated by Django 2.2.8 on 2021-05-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_auto_20210505_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='user',
            new_name='created_by',
        ),
    ]
