# Generated by Django 3.2.4 on 2022-03-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_rename_reward_related_id_wallettransaction_related_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='related_id',
            field=models.CharField(max_length=36),
        ),
    ]
