# Generated by Django 2.2.8 on 2021-05-07 20:13

import Notifications.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('redirect_url', models.URLField(max_length=256)),
                ('type', models.CharField(choices=[('BOOKINGS', 'BOOKINGS'), ('PAYMENTS', 'PAYMENTS'), ('GENERAL', 'GENERAL'), ('APPROVALS', 'APPROVALS')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], max_length=20)),
                ('data', models.CharField(max_length=1000, validators=[Notifications.validations.is_json])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
