# Generated by Django 2.2.8 on 2021-06-29 17:48

import Notifications.validations
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('redirect_url', models.URLField(max_length=256)),
                ('type', models.CharField(choices=[('BOOKINGS', 'BOOKINGS'), ('PAYMENTS', 'PAYMENTS'), ('GENERAL', 'GENERAL'), ('APPROVALS', 'APPROVALS')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], default='ACTIVE', max_length=20)),
                ('data', models.TextField(validators=[Notifications.validations.is_json])),
                ('all_users', models.BooleanField()),
                ('all_business_client', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', models.BooleanField(default=True)),
                ('bookings', models.BooleanField(default=True)),
                ('payments', models.BooleanField(default=True)),
                ('general', models.BooleanField(default=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FirebaseTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=36)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], default='ACTIVE', max_length=20)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notifications.Notification')),
            ],
            options={
                'unique_together': {('notification', 'user_id')},
            },
        ),
    ]
