# Generated by Django 2.2.8 on 2021-05-07 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='all_business_client',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='all_users',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=36)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notifications.Notification')),
            ],
            options={
                'unique_together': {('notification', 'user_id')},
            },
        ),
    ]
