# Generated by Django 2.2.8 on 2021-05-07 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_auto_20210507_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
