# Generated by Django 2.2.8 on 2021-05-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_auto_20210507_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationusers',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], default='ACTIVE', max_length=20),
        ),
    ]
