# Generated by Django 3.2.4 on 2021-06-20 03:38

import Notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_firebasetokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.CharField(default=Notifications.models.get_id, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
