# Generated by Django 2.2.8 on 2021-05-08 15:10

import HelpCenter.helpers
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=HelpCenter.helpers.upload_carousel_image)),
                ('redirection_url', models.URLField(max_length=256)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], max_length=20)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelpCenter.Carousel')),
            ],
        ),
    ]
