# Generated by Django 2.2.8 on 2021-05-25 18:36

import HelpCenter.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpCenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(max_length=300, upload_to=HelpCenter.helpers.upload_carousel_image),
        ),
    ]
