# Generated by Django 2.2.8 on 2021-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpCenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCenterFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
    ]
