# Generated by Django 2.2.8 on 2021-05-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpCenter', '0002_auto_20210508_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=30)),
                ('video_url', models.URLField(max_length=256)),
                ('title', models.CharField(max_length=30)),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='businessclientfaq',
            name='answer',
            field=models.TextField(),
        ),
    ]
