# Generated by Django 2.2.8 on 2021-05-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpCenter', '0003_auto_20210508_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='howtouse',
            old_name='entity',
            new_name='entity_type',
        ),
    ]
