# Generated by Django 3.2.4 on 2022-03-04 15:21

import HelpCenter.helpers
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpCenter', '0006_alter_carouselitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(max_length=300, storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=HelpCenter.helpers.upload_carousel_image),
        ),
    ]
