# Generated by Django 3.2.4 on 2021-07-04 06:10

import ChillBro.validations
import EmployeeManagement.helpers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdProofs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=36, verbose_name='Employee')),
                ('pan_no', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), ChillBro.validations.validate_pan], verbose_name='PAN No')),
                ('aadhar_no', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14), ChillBro.validations.validate_aadhar], verbose_name='Aadhar No')),
                ('pan_image', models.ImageField(max_length=500, upload_to=EmployeeManagement.helpers.upload_pan_image_for_employee)),
                ('aadhar_image', models.ImageField(max_length=500, upload_to=EmployeeManagement.helpers.upload_aadhar_image_for_employee)),
            ],
        ),
        migrations.CreateModel(
            name='MYCEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=36, unique=True, verbose_name='Employee')),
                ('department', models.CharField(choices=[('HR', 'HR'), ('CUSTOMER_CARE', 'CUSTOMER_CARE'), ('MARKETING', 'MARKETING'), ('LEGAL', 'LEGAL')], max_length=50, verbose_name='Department')),
                ('reporting_manager', models.CharField(max_length=36, null=True, verbose_name='Reporting Manager')),
                ('joining_date', models.DateTimeField(verbose_name='Joining Date')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=36, unique=True, verbose_name='Employee ID')),
                ('year_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=36, unique=True, verbose_name='Employee')),
                ('bank_name', models.CharField(max_length=60)),
                ('account_no', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(9), ChillBro.validations.validate_bank_account_no])),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), ChillBro.validations.validate_ifsc_code])),
                ('account_holder_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=36, verbose_name='Employee')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], max_length=36)),
                ('approved_by', models.CharField(max_length=36, verbose_name='Approved By')),
                ('leave_type', models.CharField(choices=[('SICK', 'SICK'), ('PERSONAL', 'PERSONAL'), ('CASUAL', 'CASUAL'), ('PAID', 'PAID')], max_length=36, verbose_name='Leave type')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=36, verbose_name='Employee')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'PRESENT'), ('ABSENT', 'ABSENT')], max_length=50, verbose_name='Status')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
