# Generated by Django 3.2.4 on 2021-06-24 15:31

import ChillBro.validations
import EmployeeManagement.helpers
import EmployeeManagement.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdProofs',
            fields=[
                ('id', models.CharField(default=EmployeeManagement.models.get_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('pan_no', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), ChillBro.validations.validate_pan], verbose_name='PAN No')),
                ('aadhar_no', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14), ChillBro.validations.validate_aadhar], verbose_name='Aadhar No')),
                ('pan_image', models.ImageField(max_length=500, upload_to=EmployeeManagement.helpers.upload_pan_image_for_employee)),
                ('aadhar_image', models.ImageField(max_length=500, upload_to=EmployeeManagement.helpers.upload_aadhar_image_for_employee)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAccount',
            fields=[
                ('id', models.CharField(default=EmployeeManagement.models.get_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=60)),
                ('account_no', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(9), ChillBro.validations.validate_bank_account_no])),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11), ChillBro.validations.validate_ifsc_code])),
                ('account_holder_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MYCEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=36, unique=True, verbose_name='Employee')),
                ('department', models.CharField(choices=[('HR', 'HR'), ('CUSTOMER_CARE', 'CUSTOMER_CARE'), ('MARKETING', 'MARKETING'), ('LEGAL', 'LEGAL')], max_length=50, verbose_name='Department')),
                ('reporting_manager', models.CharField(max_length=36, verbose_name='Reporting Manager')),
                ('joining_date', models.DateTimeField(verbose_name='Joining Date')),
                ('salary_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.salaryaccount', verbose_name='Salary Details')),
            ],
        ),
    ]
