# Generated by Django 3.2.4 on 2021-06-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idproofs',
            name='employee',
            field=models.CharField(max_length=36, verbose_name='Employee'),
        ),
    ]
