# Generated by Django 3.2.4 on 2021-06-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0002_alter_idproofs_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycemployee',
            name='salary_details',
        ),
    ]
