# Generated by Django 3.2.4 on 2021-06-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0003_remove_mycemployee_salary_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=36, verbose_name='Employee')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], max_length=36)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.CharField(max_length=36, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='mycemployee',
            name='reporting_manager',
            field=models.CharField(max_length=36, null=True, verbose_name='Reporting Manager'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
