# Generated by Django 3.2.4 on 2021-09-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0002_auto_20210922_2311'),
        ('EmployeeManagement', '0003_auto_20210926_1202'),
    ]

    operations = [
    ]
