# Generated by Django 3.2.4 on 2022-03-04 19:22

import EmployeeManagement.helpers
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0009_auto_20220304_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idproofs',
            name='aadhar_image',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=EmployeeManagement.helpers.upload_aadhar_image_for_employee),
        ),
        migrations.AlterField(
            model_name='idproofs',
            name='pan_image',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=EmployeeManagement.helpers.upload_pan_image_for_employee),
        ),
    ]
