# Generated by Django 2.2.8 on 2021-04-24 19:17

import UserApp.helpers
import UserApp.validations
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10), UserApp.validations.validate_phone], verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('MANAGER', 'MANAGER'), ('OWNER', 'OWNER')], max_length=100)),
                ('image', models.ImageField(upload_to=UserApp.helpers.upload_employee_image)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('business_name', models.CharField(max_length=100)),
                ('secondary_contact', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), UserApp.validations.validate_phone])),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
