# Generated by Django 2.2.8 on 2021-03-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=10, verbose_name='phone_number'),
            preserve_default=False,
        ),
    ]
