# Generated by Django 2.2.8 on 2021-05-09 08:06

import UserApp.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
        migrations.CreateModel(
            name='EmployeeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=UserApp.helpers.upload_employee_image)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Employee')),
            ],
        ),
    ]
