# Generated by Django 2.2.8 on 2021-05-25 18:36

import UserApp.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeimage',
            name='image',
            field=models.ImageField(max_length=300, upload_to=UserApp.helpers.upload_employee_image),
        ),
    ]
