# Generated by Django 2.2.8 on 2021-04-25 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20210424_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessclient',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='entity_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('SUPERVISOR', 'SUPERVISOR'), ('MANAGER', 'MANAGER'), ('OWNER', 'OWNER')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
