# Generated by Django 2.2.8 on 2021-03-28 10:44

import UserApp.validations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20210327_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10), UserApp.validations.validate_phone], verbose_name='phone_number'),
        ),
    ]
