# Generated by Django 3.2.4 on 2021-09-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_alter_employeeimage_image'),
        ('UserApp', '0005_alter_myuser_last_name'),
    ]

    operations = [
    ]
