# Generated by Django 3.2.4 on 2021-09-26 06:32

import UserApp.helpers
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_merge_20210926_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeimage',
            name='image',
            field=models.ImageField(max_length=300, storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=UserApp.helpers.upload_employee_image),
        ),
    ]
