# Generated by Django 3.2.4 on 2022-03-09 16:38

import UserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_populate_refer_earn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='refer_code',
            field=models.CharField(default=UserApp.models.generate_refer_and_earn_code, max_length=8, unique=True),
        ),
    ]
