# Generated by Django 2.2.8 on 2021-06-15 18:19

import Cart.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.CharField(default=Cart.models.get_id, max_length=36, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=36)),
                ('entity_type', models.CharField(choices=[('STAY', 'STAY'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('EVENT', 'EVENT')], max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=36)),
                ('quantity', models.IntegerField()),
                ('size', models.CharField(max_length=10, verbose_name='Size')),
                ('has_sub_products', models.BooleanField(default=False)),
                ('is_combo', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.Cart')),
                ('parent_cart_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cart.CartProducts', verbose_name='Parent Care Product Id')),
            ],
            options={
                'unique_together': {('cart', 'product_id', 'hidden', 'parent_cart_product')},
            },
        ),
    ]
