# Generated by Django 2.2.8 on 2021-05-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='entity_type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('EVENT', 'EVENT')], default='HOTEL', max_length=30),
        ),
    ]
