# Generated by Django 3.2.4 on 2021-10-03 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('slot', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(max_length=10)),
                ('alternate_no', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.cartproducts')),
            ],
        ),
        migrations.CreateModel(
            name='EventsPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('quantity', models.IntegerField(default=0)),
                ('event_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.eventsdetails')),
            ],
        ),
    ]
