# Generated by Django 2.2.8 on 2021-06-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartExtraDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(blank=True, choices=[('HOTEL', 'HOTEL'), ('RESORT', 'RESORT'), ('GUESTHOUSE', 'GUESTHOUSE'), ('DORMITORY_MEN', 'DORMITORY_MEN'), ('DORMITORY_WOMEN', 'DORMITORY_WOMEN'), ('DORMITORY_ALL', 'DORMITORY_ALL'), ('PG_MEN', 'PG_MEN'), ('PG_WOMEN', 'PG_WOMEN'), ('PG_ALL', 'PG_ALL')], max_length=30, null=True)),
                ('trip_type', models.CharField(blank=True, choices=[('ROUND', 'ROUND'), ('SINGLE', 'SINGLE')], max_length=30, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=36, null=True)),
                ('drop_location', models.CharField(blank=True, max_length=36, null=True)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.CartProducts')),
            ],
        ),
    ]
