# Generated by Django 2.2.8 on 2021-05-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='created_by',
        ),
    ]
