# Generated by Django 2.2.8 on 2021-04-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
