# Generated by Django 2.2.8 on 2021-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='size',
            field=models.CharField(default=1, max_length=10, verbose_name='Size'),
            preserve_default=False,
        ),
    ]
