# Generated by Django 2.2.8 on 2021-05-29 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_auto_20210529_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboCartProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_product_id', models.CharField(max_length=36)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.Cart')),
                ('cart_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.CartProducts')),
            ],
        ),
    ]
