# Generated by Django 2.2.8 on 2021-06-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cartextradetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartExtraDetails',
            new_name='CartProductExtraDetails',
        ),
    ]
