# Generated by Django 3.2.4 on 2022-03-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_remove_eventsdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsdetails',
            name='alternate_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='eventsdetails',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
