# Generated by Django 2.2.8 on 2021-06-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_remove_cartproductextradetails_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproductextradetails',
            name='excess_km_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='cartproductextradetails',
            name='is_infinity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproductextradetails',
            name='km_limit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproductextradetails',
            name='km_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='cartproductextradetails',
            name='single_trip_return_value_per_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
