# Generated by Django 2.2.8 on 2021-05-29 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_auto_20210529_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='parent_cart_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cart.CartProducts', verbose_name='Parent Care Product Id'),
        ),
        migrations.DeleteModel(
            name='ComboCartProducts',
        ),
    ]
