# Generated by Django 2.2.8 on 2021-06-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_auto_20210619_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproductextradetails',
            name='excess_km_price',
        ),
        migrations.RemoveField(
            model_name='cartproductextradetails',
            name='is_infinity',
        ),
        migrations.RemoveField(
            model_name='cartproductextradetails',
            name='km_limit',
        ),
        migrations.RemoveField(
            model_name='cartproductextradetails',
            name='km_price',
        ),
        migrations.RemoveField(
            model_name='cartproductextradetails',
            name='single_trip_return_value_per_km',
        ),
    ]
