# Generated by Django 2.2.8 on 2021-06-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_auto_20210619_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProductExtraDetails',
            new_name='TransportDetails',
        ),
    ]
