# Generated by Django 2.2.8 on 2021-06-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_auto_20210602_1748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproducts',
            unique_together={('cart', 'product_id', 'hidden', 'parent_cart_product')},
        ),
    ]
