# Generated by Django 2.2.8 on 2021-06-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_auto_20210621_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportdetails',
            name='km_limit_choosen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
