# Generated by Django 2.2.8 on 2021-06-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_auto_20210603_1133'),
        ('Cart', '0003_auto_20210525_2217'),
    ]

    operations = [
    ]
