# Generated by Django 2.2.8 on 2021-06-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_transportdetails_km_limit_choosen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartproducts',
            unique_together={('cart', 'product_id', 'size', 'hidden', 'parent_cart_product')},
        ),
    ]
