# Generated by Django 2.2.8 on 2021-06-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_merge_20210604_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='has_sub_products',
            field=models.BooleanField(default=False),
        ),
    ]
