# Generated by Django 2.2.8 on 2021-06-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_auto_20210627_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Size'),
        ),
    ]
