# Generated by Django 2.2.8 on 2021-06-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selfrentaldistanceprice',
            old_name='excess_price',
            new_name='excess_km_price',
        ),
        migrations.RemoveField(
            model_name='hireavehicledistanceprice',
            name='is_km_infinity',
        ),
    ]
