# Generated by Django 2.2.8 on 2021-03-21 12:16

import Product.BaseProduct.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Transport', 'Transport'), ('Rental', 'Rental')], default='Rental', max_length=30, validators=[Product.BaseProduct.models.validate_product_type], verbose_name='Product Type'),
        ),
    ]
