# Generated by Django 3.2.4 on 2021-09-18 12:42

import Product.PG.helpers
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon_url', models.ImageField(storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Product.PG.helpers.image_upload_to_pg_amenities)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('RENTAL', 'RENTAL'), ('DRIVER', 'DRIVER'), ('VEHICLE', 'VEHICLE'), ('HIRE_A_VEHICLE', 'HIRE_A_VEHICLE'), ('TRAVEL_PACKAGE_VEHICLE', 'TRAVEL_PACKAGE_VEHICLE'), ('TRAVEL_AGENCY', 'TRAVEL_AGENCY'), ('MAKE_YOUR_OWN_TRIP', 'MAKE_YOUR_OWN_TRIP'), ('SELF_RENTAL', 'SELF_RENTAL'), ('PAID_AMENITIES', 'PAID_AMENITIES'), ('EVENT', 'EVENT'), ('PG', 'PG')], default='RENTAL', max_length=30, verbose_name='Product Type'),
        ),
        migrations.CreateModel(
            name='PGRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_sharing', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='PGAvailableAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('pg_amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.pgamenities', verbose_name='PG Amenities')),
                ('pg_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.pgroom', verbose_name='PG')),
            ],
            options={
                'unique_together': {('pg_room', 'pg_amenity')},
            },
        ),
    ]
