# Generated by Django 2.2.8 on 2021-05-27 21:46

import Product.Hotel.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='icon_url',
            field=models.ImageField(default='No Image', upload_to=Product.Hotel.helpers.image_upload_to_amenities),
            preserve_default=False,
        ),
    ]
