# Generated by Django 2.2.8 on 2021-06-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireAVehicleDistancePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_type', models.CharField(choices=[('HOUR', 'HOUR'), ('DAY', 'DAY'), ('WEEK', 'WEEK')], default='HOUR', max_length=30)),
                ('km_limit', models.PositiveIntegerField()),
                ('km_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('excess_km_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('is_infinity', models.BooleanField(default=False)),
                ('trip_type', models.CharField(choices=[('ROUND', 'ROUND'), ('SINGLE', 'SINGLE')], default='ROUND', max_length=30)),
                ('single_trip_return_value_per_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('min_duration', models.PositiveIntegerField(default=1)),
                ('max_duration', models.PositiveIntegerField(default=30)),
                ('hire_a_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.HireAVehicle')),
            ],
            options={
                'unique_together': {('hire_a_vehicle', 'duration_type')},
            },
        ),
    ]
