# Generated by Django 2.2.8 on 2021-04-26 10:59

import Product.Seller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller_id',
            field=models.CharField(default=Product.Seller.models.getId, max_length=36, primary_key=True, serialize=False),
        ),
    ]
