# Generated by Django 2.2.8 on 2021-05-18 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_combo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ComboProductItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_item', to='Product.Product', verbose_name='Combo Item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Product', verbose_name='Product')),
            ],
        ),
    ]
