# Generated by Django 2.2.8 on 2021-04-23 22:56

import Product.BaseProduct.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='order',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('DELETED', 'DELETED')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Transport', 'Transport'), ('Rental', 'Rental')], default='Rental', max_length=30, validators=[Product.BaseProduct.models.validate_product_type], verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='categoryimage',
            unique_together={('category', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'order')},
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=16)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Product', verbose_name='Product Seller')),
            ],
            options={
                'unique_together': {('product', 'seller_id')},
            },
        ),
    ]
