# Generated by Django 2.2.8 on 2021-06-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='category_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Product.CategoryProduct', verbose_name='Category Product'),
            preserve_default=False,
        ),
    ]
