# Generated by Django 3.2.4 on 2021-06-25 16:36

import Product.TravelAgency.helpers
import Product.TravelAgency.validations
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.ImageField(max_length=300, upload_to=Product.TravelAgency.helpers.upload_image_to_travel_characteristics)),
            ],
        ),
        migrations.AlterModelOptions(
            name='packageplaces',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='packageplaces',
            name='duration_to_reach',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packageplaces',
            name='spending_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('RENTAL', 'RENTAL'), ('DRIVER', 'DRIVER'), ('VEHICLE', 'VEHICLE'), ('HIRE_A_VEHICLE', 'HIRE_A_VEHICLE'), ('TRAVEL_PACKAGE_VEHICLE', 'TRAVEL_PACKAGE_VEHICLE'), ('TRAVEL_AGENCY', 'TRAVEL_AGENCY'), ('MAKE_YOUR_OWN_TRIP', 'MAKE_YOUR_OWN_TRIP'), ('SELF_RENTAL', 'SELF_RENTAL')], default='RENTAL', max_length=30, verbose_name='Product Type'),
        ),
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duration in days')),
                ('duration_in_nights', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duration in nights')),
                ('tags', models.TextField(validators=[Product.TravelAgency.validations.is_json])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='MakeYourOwnTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='TravelAgencyPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PLACE', 'PLACE'), ('STAY', 'STAY'), ('FOOD', 'FOOD')], max_length=20)),
                ('day_number', models.IntegerField(verbose_name='Day Number')),
                ('order', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.place', verbose_name='Agency Place')),
                ('travel_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.travelagency', verbose_name='Travel Agency')),
            ],
            options={
                'unique_together': {('travel_agency', 'place', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TravelAgencyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Product.TravelAgency.helpers.image_upload_to_travel_agency)),
                ('order', models.IntegerField()),
                ('travel_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.travelagency', verbose_name='Travel Agency')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('travel_agency', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TravelAgencyCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.travelagency')),
                ('travel_characteristics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.travelcharacteristics')),
            ],
            options={
                'unique_together': {('travel_agency', 'travel_characteristics')},
            },
        ),
        migrations.CreateModel(
            name='MakeYourOwnTripPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_your_own_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.makeyourowntrip', verbose_name='Make Your Own Trip')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.place', verbose_name='Make Your Own Trip Place')),
            ],
            options={
                'unique_together': {('make_your_own_trip', 'place')},
            },
        ),
    ]
