# Generated by Django 2.2.8 on 2021-06-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecharacteristics',
            name='display_front',
            field=models.BooleanField(default=False),
        ),
    ]
