# Generated by Django 2.2.8 on 2021-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
