# Generated by Django 2.2.8 on 2021-05-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerproduct',
            name='selling_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('DELETED', 'DELETED')], default='PENDING', max_length=30),
        ),
    ]
