# Generated by Django 2.2.8 on 2021-05-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210518_2122'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comboproductitems',
            unique_together={('product', 'combo_item')},
        ),
    ]
