# Generated by Django 2.2.8 on 2021-03-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'order')},
        ),
    ]
