# Generated by Django 2.2.8 on 2021-06-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_hireavehicledistanceprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hireavehicledistanceprice',
            old_name='max_duration',
            new_name='max_time_duration',
        ),
        migrations.RenameField(
            model_name='hireavehicledistanceprice',
            old_name='min_duration',
            new_name='min_time_duration',
        ),
    ]
