# Generated by Django 3.2.4 on 2021-08-16 16:09

import Product.Events.validations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_vehiclesdrivenbydriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('ONLINE/OFFLINE', 'ONLINE/OFFLINE')], default='OFFLINE', max_length=30, verbose_name='Event Mode')),
                ('host_app', models.CharField(blank=True, choices=[('ZOOM', 'ZOOM'), ('MICROSOFT TEAMS', 'MICROSOFT TEAMS'), ('GOOGLE MEET', 'GOOGLE MEET')], max_length=30, null=True, verbose_name='Event Mode')),
                ('url_link', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_type', models.CharField(choices=[('PAID', 'PAID'), ('FREE', 'FREE')], default='PAID', max_length=30, verbose_name='Event Payment Type')),
                ('has_slots', models.BooleanField(default=False, verbose_name='Has Slots?')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('tags', models.TextField(validators=[Product.Events.validations.is_json])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='EventSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day_start_time', models.TimeField()),
                ('day_end_time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.events', verbose_name='Event')),
            ],
            options={
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EventPriceClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.events', verbose_name='Event')),
            ],
            options={
                'unique_together': {('event', 'name')},
            },
        ),
    ]
