# Generated by Django 2.2.8 on 2021-04-26 11:00

import Product.Seller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210426_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='id',
            field=models.CharField(default=Product.Seller.models.getId, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller_id',
            field=models.CharField(max_length=36),
        ),
    ]
