# Generated by Django 2.2.8 on 2021-06-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_place_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address_id',
            field=models.CharField(default='', max_length=36),
            preserve_default=False,
        ),
    ]
