# Generated by Django 2.2.8 on 2021-06-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_travelpackage_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.VehicleType', verbose_name='VehicleType'),
        ),
        migrations.CreateModel(
            name='TravelPackageVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.Product', verbose_name='Product')),
                ('travel_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_for_vehicle', to='Product.TravelPackage', verbose_name='Default Driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_package_vehicle', to='Product.Product', verbose_name='Vehicle')),
            ],
        ),
    ]
