# Generated by Django 2.2.8 on 2021-04-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210427_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller_id',
            field=models.CharField(max_length=36),
        ),
    ]
