# Generated by Django 3.2.4 on 2021-06-26 11:44

import Product.Category.helpers
from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210625_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_url',
            field=thumbnails.fields.ImageField(max_length=300, upload_to=Product.Category.helpers.update_image_to_category_icon),
        ),
    ]
