# Generated by Django 3.2.4 on 2021-09-19 02:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210918_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagency',
            name='starting_point',
            field=models.CharField(choices=[('VSKP', 'VISAKHAPATNAM'), ('SRKL', 'SRIKAKULAM'), ('VYZY', 'VIJAYANAGARAM'), ('EG', 'EAST GODAVARI'), ('WG', 'WEST GODAVARI')], default=10, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='starting_point',
            field=models.CharField(choices=[('VSKP', 'VISAKHAPATNAM'), ('SRKL', 'SRIKAKULAM'), ('VYZY', 'VIJAYANAGARAM'), ('EG', 'EAST GODAVARI'), ('WG', 'WEST GODAVARI')], default=django.utils.timezone.now, max_length=36),
            preserve_default=False,
        ),
    ]
