# Generated by Django 2.2.8 on 2021-06-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210617_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireavehicledistanceprice',
            name='trip_type',
        ),
    ]
