# Generated by Django 3.2.4 on 2021-08-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_eventpriceclasses_events_eventslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('RENTAL', 'RENTAL'), ('DRIVER', 'DRIVER'), ('VEHICLE', 'VEHICLE'), ('HIRE_A_VEHICLE', 'HIRE_A_VEHICLE'), ('TRAVEL_PACKAGE_VEHICLE', 'TRAVEL_PACKAGE_VEHICLE'), ('TRAVEL_AGENCY', 'TRAVEL_AGENCY'), ('MAKE_YOUR_OWN_TRIP', 'MAKE_YOUR_OWN_TRIP'), ('SELF_RENTAL', 'SELF_RENTAL'), ('EVENT', 'EVENT')], default='RENTAL', max_length=30, verbose_name='Product Type'),
        ),
    ]
