# Generated by Django 2.2.8 on 2021-03-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210321_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='categoryimage',
            unique_together={('category', 'order')},
        ),
    ]
