# Generated by Django 2.2.8 on 2021-06-11 18:01

import Product.TravelPackages.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210609_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='tags',
            field=models.TextField(default=[], validators=[Product.TravelPackages.validations.is_json]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('RENTAL', 'RENTAL'), ('DRIVER', 'DRIVER'), ('VEHICLE', 'VEHICLE'), ('HIRE_A_VEHICLE', 'HIRE_A_VEHICLE'), ('TRAVEL_PACKAGE_VEHICLE', 'TRAVEL_PACKAGE_VEHICLE')], default='RENTAL', max_length=30, verbose_name='Product Type'),
        ),
    ]
