# Generated by Django 2.2.8 on 2021-06-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_hireavehicledistanceprice_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireavehicledistanceprice',
            name='excess_duration_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
