# Generated by Django 2.2.8 on 2021-05-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20210519_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order']},
        ),
    ]
