# Generated by Django 2.2.8 on 2021-05-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20210426_2036'),
        ('Product', '0003_auto_20210430_2315'),
    ]

    operations = [
    ]
