# Generated by Django 2.2.8 on 2021-05-08 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_merge_20210503_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('max_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('min_discount', models.IntegerField(default=0)),
                ('max_discount', models.IntegerField(default=0)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.Category')),
            ],
        ),
    ]
