# Generated by Django 2.2.8 on 2021-06-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_hireavehicledistanceprice_excess_duration_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hireavehicledistanceprice',
            old_name='is_infinity',
            new_name='is_km_infinity',
        ),
        migrations.AlterUniqueTogether(
            name='hireavehicledistanceprice',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='HireAVehicleDurationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_hour_limit', models.PositiveIntegerField()),
                ('km_day_limit', models.PositiveIntegerField()),
                ('min_hour_duration', models.PositiveIntegerField(default=1)),
                ('max_hour_duration', models.PositiveIntegerField(default=24)),
                ('min_day_duration', models.PositiveIntegerField(default=1)),
                ('max_day_duration', models.PositiveIntegerField(default=31)),
                ('hire_a_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.HireAVehicle')),
            ],
        ),
        migrations.RemoveField(
            model_name='hireavehicledistanceprice',
            name='duration_type',
        ),
        migrations.RemoveField(
            model_name='hireavehicledistanceprice',
            name='km_limit',
        ),
        migrations.RemoveField(
            model_name='hireavehicledistanceprice',
            name='max_time_duration',
        ),
        migrations.RemoveField(
            model_name='hireavehicledistanceprice',
            name='min_time_duration',
        ),
    ]
