# Generated by Django 2.2.8 on 2021-05-20 15:14

import Product.Category.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20210519_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_url',
            field=models.ImageField(max_length=300, upload_to=Product.Category.helpers.update_image_to_category_icon),
        ),
    ]
