# Generated by Django 2.2.8 on 2021-03-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_sellerproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sellerproduct',
            unique_together={('product', 'seller_id')},
        ),
    ]
