# Generated by Django 2.2.8 on 2021-06-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20210620_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireavehicledistanceprice',
            name='excess_duration_price',
        ),
        migrations.AddField(
            model_name='hireavehicledurationdetails',
            name='excess_day_duration_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='hireavehicledurationdetails',
            name='excess_hour_duration_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
