# Generated by Django 2.2.8 on 2021-06-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20210621_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireavehicledurationdetails',
            name='excess_day_duration_price',
        ),
        migrations.RemoveField(
            model_name='hireavehicledurationdetails',
            name='excess_hour_duration_price',
        ),
        migrations.RemoveField(
            model_name='hireavehicledurationdetails',
            name='km_day_limit',
        ),
        migrations.RemoveField(
            model_name='hireavehicledurationdetails',
            name='km_hour_limit',
        ),
        migrations.AddField(
            model_name='hireavehicledistanceprice',
            name='excess_day_duration_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='hireavehicledistanceprice',
            name='excess_hour_duration_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='hireavehicledistanceprice',
            name='km_day_limit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hireavehicledistanceprice',
            name='km_hour_limit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
