# Generated by Django 2.2.8 on 2021-04-22 15:53

import Product.Category.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20210327_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_url',
            field=models.ImageField(default='vamsi', upload_to=Product.Category.helpers.iconUrlImage),
            preserve_default=False,
        ),
    ]
