# Generated by Django 3.2.4 on 2021-10-30 11:15

import Product.Dormitory.helpers
import Product.PG.helpers
import Product.Resort.helpers
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20210928_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon_url', models.ImageField(storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Product.Dormitory.helpers.image_upload_to_dormitory_amenities)),
            ],
        ),
        migrations.CreateModel(
            name='PGAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon_url', models.ImageField(storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Product.PG.helpers.image_upload_to_pg_amenities)),
            ],
        ),
        migrations.CreateModel(
            name='ResortAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon_url', models.ImageField(storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Product.Resort.helpers.image_upload_to_resort_amenities)),
            ],
        ),
        migrations.AddField(
            model_name='travelagency',
            name='starting_point',
            field=models.CharField(choices=[('VSKP', 'VISAKHAPATNAM'), ('SRKL', 'SRIKAKULAM'), ('VYZY', 'VIJAYANAGARAM'), ('EG', 'EAST GODAVARI'), ('WG', 'WEST GODAVARI')], default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='starting_point',
            field=models.CharField(choices=[('VSKP', 'VISAKHAPATNAM'), ('SRKL', 'SRIKAKULAM'), ('VYZY', 'VIJAYANAGARAM'), ('EG', 'EAST GODAVARI'), ('WG', 'WEST GODAVARI')], default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('RENTAL', 'RENTAL'), ('DRIVER', 'DRIVER'), ('VEHICLE', 'VEHICLE'), ('HIRE_A_VEHICLE', 'HIRE_A_VEHICLE'), ('TRAVEL_PACKAGE_VEHICLE', 'TRAVEL_PACKAGE_VEHICLE'), ('TRAVEL_AGENCY', 'TRAVEL_AGENCY'), ('MAKE_YOUR_OWN_TRIP', 'MAKE_YOUR_OWN_TRIP'), ('SELF_RENTAL', 'SELF_RENTAL'), ('EVENT', 'EVENT'), ('PAID_AMENITIES', 'PAID_AMENITIES'), ('PG', 'PG'), ('DORMITORY', 'DORMITORY'), ('RESORT', 'RESORT')], default='RENTAL', max_length=30, verbose_name='Product Type'),
        ),
        migrations.CreateModel(
            name='ResortRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='PGRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_sharing', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='PaidAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='DormitoryRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='ResortAvailableAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('resort_amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.resortamenities', verbose_name='Resort Amenities')),
                ('resort_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.resortroom', verbose_name='Resort')),
            ],
            options={
                'unique_together': {('resort_room', 'resort_amenity')},
            },
        ),
        migrations.CreateModel(
            name='PGAvailableAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('pg_amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.pgamenities', verbose_name='PG Amenities')),
                ('pg_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.pgroom', verbose_name='PG')),
            ],
            options={
                'unique_together': {('pg_room', 'pg_amenity')},
            },
        ),
        migrations.CreateModel(
            name='DormitoryAvailableAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('dormitory_amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.dormitoryamenities', verbose_name='Dormitory Amenities')),
                ('dormitory_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.dormitoryroom', verbose_name='Dormitory')),
            ],
            options={
                'unique_together': {('dormitory_room', 'dormitory_amenity')},
            },
        ),
    ]
