# Generated by Django 2.2.8 on 2021-06-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20210621_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistancePrice',
            new_name='SelfRentalDistancePrice',
        ),
        migrations.RenameField(
            model_name='hireavehicledistanceprice',
            old_name='km_price',
            new_name='day_price',
        ),
        migrations.AddField(
            model_name='hireavehicledistanceprice',
            name='hour_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.CreateModel(
            name='SelfRentalDurationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_hour_duration', models.PositiveIntegerField(default=1)),
                ('max_hour_duration', models.PositiveIntegerField(default=24)),
                ('min_day_duration', models.PositiveIntegerField(default=1)),
                ('max_day_duration', models.PositiveIntegerField(default=31)),
                ('self_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.SelfRental')),
            ],
        ),
    ]
