# Generated by Django 2.2.8 on 2021-05-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20210521_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='productsize',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('product', 'size'), ('product', 'order')},
        ),
    ]
