# Generated by Django 2.2.8 on 2021-05-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20210521_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Order'),
        ),
    ]
