# Generated by Django 2.2.8 on 2021-06-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20210622_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireavehicledistanceprice',
            name='day_price',
        ),
        migrations.RemoveField(
            model_name='hireavehicledistanceprice',
            name='excess_day_duration_price',
        ),
        migrations.RemoveField(
            model_name='hireavehicledistanceprice',
            name='excess_hour_duration_price',
        ),
        migrations.RemoveField(
            model_name='hireavehicledistanceprice',
            name='hour_price',
        ),
        migrations.AddField(
            model_name='hireavehicledurationdetails',
            name='day_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='hireavehicledurationdetails',
            name='excess_day_duration_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='hireavehicledurationdetails',
            name='excess_hour_duration_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='hireavehicledurationdetails',
            name='hour_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
