# Generated by Django 2.2.8 on 2021-05-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_auto_20210521_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comboproductitems',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='comboproductitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
