# Generated by Django 3.2.4 on 2021-11-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20211106_1156'),
        ('Product', '0011_auto_20211117_2339'),
    ]

    operations = [
    ]
