# Generated by Django 2.2.8 on 2021-05-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20210519_2143'),
        ('Product', '0011_auto_20210522_1334'),
    ]

    operations = [
    ]
