# Generated by Django 3.2.4 on 2021-12-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_auto_20211214_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackagevehicle',
            name='travel_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_package', to='Product.product', verbose_name='Travel Package'),
        ),
    ]
