# Generated by Django 2.2.8 on 2021-05-09 11:38

import ReviewsRatings.helpers
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_id', models.CharField(max_length=36, verbose_name='Related Id')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'unique_together': {('related_id', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ReviewsRatings.helpers.image_upload_to_review)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReviewsRatings.ReviewsRatings')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAndSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('category', models.CharField(choices=[('SUGGESTION', 'SUGGESTION'), ('SOMETHING IS NOT QUITE RIGHT', 'SOMETHING IS NOT QUITE RIGHT'), ('COMPLIMENT', 'COMPLIMENT')], default='SUGGESTION', max_length=30)),
                ('comment', models.CharField(max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
        ),
    ]
