# Generated by Django 2.2.8 on 2021-05-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsRatings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsratings',
            name='secondary_related_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
