# Generated by Django 2.2.8 on 2021-05-08 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsRatings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsratings',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
