# Generated by Django 2.2.8 on 2021-05-02 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReviewsRatings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsratings',
            old_name='reviewed_by',
            new_name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='reviewsratings',
            unique_together={('related_id', 'created_by')},
        ),
    ]
