# Generated by Django 2.2.8 on 2021-05-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsRatings', '0002_reviewsratings_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsratings',
            old_name='time',
            new_name='reviwed_time',
        ),
    ]
