# Generated by Django 2.2.8 on 2021-05-16 09:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReviewsRatings', '0002_reviewsratings_secondary_related_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewsratings',
            unique_together={('related_id', 'secondary_related_id', 'created_by')},
        ),
    ]
