# Generated by Django 2.2.8 on 2021-05-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsRatings', '0003_auto_20210426_0016'),
        ('ReviewsRatings', '0002_auto_20210502_1316'),
    ]

    operations = [
    ]
