# Generated by Django 2.2.8 on 2021-05-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsRatings', '0003_auto_20210509_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsratings',
            old_name='reviwed_time',
            new_name='reviewed_time',
        ),
    ]
