# Generated by Django 2.2.8 on 2021-05-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsRatings', '0003_auto_20210516_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsratings',
            name='rating_type',
            field=models.CharField(default='OVERALL', max_length=30),
        ),
    ]
