# Generated by Django 2.2.8 on 2021-05-23 01:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReviewsRatings', '0004_reviewsratings_rating_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewsratings',
            unique_together={('related_id', 'secondary_related_id', 'rating_type', 'created_by')},
        ),
    ]
