# Generated by Django 2.2.8 on 2021-05-03 23:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReviewsRatings', '0004_merge_20210503_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAndSuggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('category', models.CharField(choices=[('SUGGESTION', 'SUGGESTION'), ('SOMETHING IS NOT QUITE RIGHT', 'SOMETHING IS NOT QUITE RIGHT'), ('COMPLIMENT', 'COMPLIMENT')], default='SUGGESTION', max_length=30)),
                ('comment', models.CharField(max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
        ),
    ]
