# Generated by Django 3.2.4 on 2022-03-04 15:21

import ReviewsRatings.helpers
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsRatings', '0006_alter_reviewimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(max_length=300, storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=ReviewsRatings.helpers.image_upload_to_review),
        ),
    ]
