# Generated by Django 3.2.4 on 2022-03-09 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsRatings', '0010_customerapprating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bcappfeedbackandsuggestions',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='customerappfeedbackandsuggestions',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='customerapprating',
            name='submitted_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
