# Generated by Django 3.2.4 on 2022-03-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewsRatings', '0012_bcapprating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsratings',
            name='secondary_related_id',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
