# Generated by Django 2.2.8 on 2021-02-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=10)),
                ('address_line', models.CharField(max_length=250)),
                ('extend_address', models.CharField(blank=True, max_length=250, null=True)),
                ('landmark', models.CharField(max_length=250)),
                ('city', models.CharField(choices=[('VSKP', 'VISAKHAPATNAM')], default='VISAKHAPATNAM', max_length=30)),
                ('state', models.CharField(choices=[('AP', 'ANDHRA PRADESH')], default='ANDHRA PRADESH', max_length=30)),
                ('country', models.CharField(choices=[('IND', 'INDIA')], default='INDIA', max_length=30)),
                ('latitude', models.CharField(blank=True, max_length=15, null=True)),
                ('longitude', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
