# Generated by Django 3.2.4 on 2021-06-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('VISAKHAPATNAM', 'VISAKHAPATNAM')], default='VISAKHAPATNAM', max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('INDIA', 'INDIA')], default='INDIA', max_length=30, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('ANDHRA PRADESH', 'ANDHRA PRADESH')], default='ANDHRA PRADESH', max_length=30, verbose_name='State'),
        ),
    ]
