# Generated by Django 2.2.8 on 2021-04-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0002_auto_20210303_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address Line'),
        ),
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Landmark'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number'),
        ),
    ]
