# Generated by Django 3.2.4 on 2021-11-23 16:51

import Address.helpers1
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0003_alter_address_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('short_name', models.CharField(max_length=30, unique=True)),
                ('icon_url', models.ImageField(max_length=300, storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=Address.helpers1.upload_image_to_city_icon)),
            ],
        ),
    ]
