# Generated by Django 2.2.8 on 2021-04-29 00:58

import Address.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0003_auto_20210429_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.CharField(default=Address.models.getId, max_length=36, primary_key=True, serialize=False),
        ),
    ]
