# Generated by Django 3.2.4 on 2022-03-04 15:21

import Address.helpers
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0006_alter_cities_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='image_url',
            field=models.ImageField(max_length=300, storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Address.helpers.upload_image_to_city_icon),
        ),
    ]
