# Generated by Django 3.2.4 on 2021-07-04 10:20

import JobPortal.models
import JobPortal.validations
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(default=JobPortal.models.get_id, max_length=36, primary_key=True, serialize=False, verbose_name='Job Id')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('basic_qualifications', models.TextField(validators=[JobPortal.validations.is_json])),
                ('preferred_qualifications', models.TextField(validators=[JobPortal.validations.is_json])),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'FULL_TIME'), ('PART_TIME', 'PART_TIME')], default='FULL_TIME', max_length=30)),
                ('job_category', models.CharField(choices=[('SOFTWARE_DEVELOPMENT', 'SOFTWARE_DEVELOPMENT'), ('MARKETING_EXECUTIVE', 'MARKETING_EXECUTIVE')], default='SOFTWARE_DEVELOPMENT', max_length=50, verbose_name='Job Category')),
                ('city', models.CharField(choices=[('VISAKHAPATNAM', 'VISAKHAPATNAM')], default='VISAKHAPATNAM', max_length=30, verbose_name='City')),
                ('state', models.CharField(choices=[('ANDHRA PRADESH', 'ANDHRA PRADESH')], default='ANDHRA PRADESH', max_length=30, verbose_name='State')),
                ('country', models.CharField(choices=[('INDIA', 'INDIA')], default='INDIA', max_length=30, verbose_name='Country')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.CharField(default=JobPortal.models.get_id, max_length=36, primary_key=True, serialize=False, verbose_name='Job Application Id')),
                ('is_withdrawn', models.BooleanField(default=False, verbose_name='Is withdrawn')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[('YET_TO_VIEW', 'YET_TO_VIEW'), ('VIEWED', 'VIEWED'), ('SHORT_LISTED', 'SHORT_LISTED'), ('REJECTED', 'REJECTED')], default='YET_TO_VIEW', max_length=50, verbose_name='Application Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applied by')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobPortal.job', verbose_name='Job')),
            ],
            options={
                'unique_together': {('job', 'created_by')},
            },
        ),
    ]
