# Generated by Django 3.2.4 on 2021-08-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(choices=[('VISAKHAPATNAM', 'VISAKHAPATNAM'), ('SRIKAKULAM', 'SRIKAKULAM'), ('VIJAYANAGARAM', 'VIJAYANAGARAM'), ('EAST GODAVARI', 'EAST GODAVARI'), ('WEST GODAVARI', 'WEST GODAVARI')], default='VISAKHAPATNAM', max_length=30, verbose_name='City'),
        ),
    ]
