# Generated by Django 3.2.4 on 2021-06-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(choices=[('SOFTWARE_DEVELOPMENT', 'SOFTWARE_DEVELOPMENT'), ('MARKETING_EXECUTIVE', 'MARKETING_EXECUTIVE')], default='SOFTWARE_DEVELOPMENT', max_length=50, verbose_name='Job Category'),
        ),
    ]
