# Generated by Django 3.2.4 on 2021-06-25 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobPortal', '0002_alter_job_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplications',
            old_name='applied_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplications',
            unique_together={('job', 'created_by')},
        ),
    ]
