# Generated by Django 3.2.4 on 2021-06-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0003_auto_20210625_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='application_status',
            field=models.CharField(choices=[('YET_TO_VIEW', 'YET_TO_VIEW'), ('VIEWED', 'VIEWED'), ('SHORT_LISTED', 'SHORT_LISTED'), ('REJECTED', 'REJECTED')], default='YET_TO_VIEW', max_length=50, verbose_name='Application Status'),
        ),
    ]
