# Generated by Django 2.2.8 on 2021-04-23 22:56

import Entity.helpers
import Entity.validations
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myentity',
            name='aadhar_image',
            field=models.ImageField(default='1', upload_to=Entity.helpers.image_upload_aadhar),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myentity',
            name='aadhar_no',
            field=models.CharField(default='1', max_length=14, validators=[django.core.validators.MinLengthValidator(14), Entity.validations.validate_aadhar]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myentity',
            name='active_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='myentity',
            name='city',
            field=models.CharField(choices=[('VSKP', 'VISAKHAPATNAM')], default='VISAKHAPATNAM', max_length=30, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='myentity',
            name='gst_image',
            field=models.ImageField(default='1', upload_to=Entity.helpers.image_upload_gst),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myentity',
            name='gst_in',
            field=models.CharField(default='1', max_length=15, validators=[django.core.validators.MinLengthValidator(15), Entity.validations.validate_gst]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myentity',
            name='pan_image',
            field=models.ImageField(default='1', upload_to=Entity.helpers.image_upload_pan),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myentity',
            name='pan_no',
            field=models.CharField(default='1', max_length=10, validators=[django.core.validators.MinLengthValidator(10), Entity.validations.validate_pan]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myentity',
            name='pincode',
            field=models.CharField(default='1', max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Pincode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myentity',
            name='registration_image',
            field=models.ImageField(default='1', upload_to=Entity.helpers.image_upload_registration),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myentity',
            name='registration_no',
            field=models.CharField(default='1', max_length=21, validators=[django.core.validators.MinLengthValidator(21), Entity.validations.validate_registration]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myentity',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], default='ONLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='myentity',
            name='supervisor_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myentity',
            name='type',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Transport', 'Transport'), ('Rental', 'Rental')], default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myentity',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='myentity',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='BusinessClientEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.MyEntity', verbose_name='Booking Id')),
            ],
            options={
                'unique_together': {('entity_id', 'business_client_id')},
            },
        ),
    ]
