# Generated by Django 2.2.8 on 2021-04-27 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Entity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myentity',
            name='verified_status',
        ),
        migrations.AddField(
            model_name='myentity',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myentity',
            name='active_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EntityVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_status', models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('REJECTED', 'REJECTED'), ('YET_TO_VERIFY', 'YET_TO_VERIFY')], default='YET_TO_VERIFY', max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Entity.MyEntity', verbose_name='Entity')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
