# Generated by Django 2.2.8 on 2021-05-19 21:43

import Entity.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myentity',
            name='aadhar_image',
            field=models.ImageField(max_length=500, upload_to=Entity.helpers.upload_aadhar_image_for_entity),
        ),
        migrations.AlterField(
            model_name='myentity',
            name='gst_image',
            field=models.ImageField(max_length=500, upload_to=Entity.helpers.upload_gst_image_for_entity),
        ),
        migrations.AlterField(
            model_name='myentity',
            name='pan_image',
            field=models.ImageField(max_length=500, upload_to=Entity.helpers.upload_pan_image_for_entity),
        ),
        migrations.AlterField(
            model_name='myentity',
            name='registration_image',
            field=models.ImageField(max_length=500, upload_to=Entity.helpers.upload_registration_image_for_entity),
        ),
        migrations.AlterField(
            model_name='myentity',
            name='type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('EVENT', 'EVENT')], max_length=30),
        ),
    ]
