# Generated by Django 2.2.8 on 2021-05-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myentity',
            options={'ordering': ['-created_at']},
        ),
    ]
