# Generated by Django 2.2.8 on 2021-02-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myentity',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
