# Generated by Django 2.2.8 on 2021-05-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0002_auto_20210512_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myentity',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], default='OFFLINE', max_length=30),
        ),
    ]
