# Generated by Django 2.2.8 on 2021-05-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0002_auto_20210520_1514'),
        ('Entity', '0002_auto_20210519_2143'),
    ]

    operations = [
    ]
