# Generated by Django 2.2.8 on 2021-05-25 19:19

import Entity.helpers
import Entity.validations
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0003_merge_20210525_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRegistration',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('pan_no', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), Entity.validations.validate_pan])),
                ('registration_no', models.CharField(max_length=21, validators=[django.core.validators.MinLengthValidator(21), Entity.validations.validate_registration])),
                ('gst_in', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15), Entity.validations.validate_gst])),
                ('aadhar_no', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(14), Entity.validations.validate_aadhar])),
                ('pan_image', models.ImageField(max_length=500, upload_to=Entity.helpers.upload_pan_image_for_entity)),
                ('registration_image', models.ImageField(max_length=500, upload_to=Entity.helpers.upload_registration_image_for_entity)),
                ('gst_image', models.ImageField(max_length=500, upload_to=Entity.helpers.upload_gst_image_for_entity)),
                ('aadhar_image', models.ImageField(max_length=500, upload_to=Entity.helpers.upload_aadhar_image_for_entity)),
            ],
        ),
        migrations.RemoveField(
            model_name='myentity',
            name='aadhar_image',
        ),
        migrations.RemoveField(
            model_name='myentity',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='myentity',
            name='gst_image',
        ),
        migrations.RemoveField(
            model_name='myentity',
            name='gst_in',
        ),
        migrations.RemoveField(
            model_name='myentity',
            name='pan_image',
        ),
        migrations.RemoveField(
            model_name='myentity',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='myentity',
            name='registration_image',
        ),
        migrations.RemoveField(
            model_name='myentity',
            name='registration_no',
        ),
        migrations.AlterField(
            model_name='entityupi',
            name='upi_id',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5), Entity.validations.validate_upi_id]),
        ),
        migrations.AddField(
            model_name='myentity',
            name='registration',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Entity.EntityRegistration'),
            preserve_default=False,
        ),
    ]
