# Generated by Django 2.2.8 on 2021-04-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0003_auto_20210424_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myentity',
            name='supervisor_id',
        ),
    ]
