# Generated by Django 3.2.4 on 2021-09-28 16:17

import Entity.helpers
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0004_merge_0002_auto_20210922_2311_0003_auto_20210926_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='icon_url',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Entity.helpers.image_upload_to_amenities),
        ),
        migrations.AlterField(
            model_name='entityimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Entity.helpers.upload_image_for_entity),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='aadhar_image',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Entity.helpers.upload_aadhar_image_for_entity),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='gst_image',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Entity.helpers.upload_gst_image_for_entity),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='pan_image',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Entity.helpers.upload_pan_image_for_entity),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='registration_image',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage('django.core.files.storage.FileSystemStorage'), upload_to=Entity.helpers.upload_registration_image_for_entity),
        ),
    ]
