# Generated by Django 2.2.8 on 2021-05-27 22:29

import Entity.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0005_auto_20210525_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon_url', models.ImageField(upload_to=Entity.helpers.image_upload_to_amenities)),
            ],
        ),
        migrations.CreateModel(
            name='EntityAvailableAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.Amenities', verbose_name='Amenities')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.MyEntity', verbose_name='Entity')),
            ],
            options={
                'unique_together': {('entity', 'amenity')},
            },
        ),
    ]
