# Generated by Django 2.2.8 on 2021-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0006_amenities_entityavailableamenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='myentity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
