# Generated by Django 3.2.4 on 2021-12-04 07:41

import Entity.helpers
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0007_auto_20211127_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='icon_url',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=Entity.helpers.image_upload_to_amenities),
        ),
        migrations.AlterField(
            model_name='entityimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=Entity.helpers.upload_image_for_entity),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='aadhar_image',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=Entity.helpers.upload_aadhar_image_for_entity),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='gst_image',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=Entity.helpers.upload_gst_image_for_entity),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='pan_image',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=Entity.helpers.upload_pan_image_for_entity),
        ),
        migrations.AlterField(
            model_name='entityregistration',
            name='registration_image',
            field=models.ImageField(max_length=500, storage=django.core.files.storage.FileSystemStorage('/home/ffs2imp1oh0k/public_html/chillbro_backend/'), upload_to=Entity.helpers.upload_registration_image_for_entity),
        ),
    ]
