# Generated by Django 2.2.8 on 2021-05-28 22:25

import Entity.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0007_myentity_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Entity.helpers.upload_image_for_entity)),
                ('order', models.IntegerField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.MyEntity')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('entity', 'order')},
            },
        ),
    ]
