# Generated by Django 2.2.8 on 2021-05-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='object_id',
            field=models.CharField(max_length=36),
        ),
    ]
