# Generated by Django 2.2.8 on 2021-05-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedProductTypesRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_types', models.TextField(blank=True, null=True, verbose_name='Product Types')),
                ('all_product_types', models.BooleanField(default=True, verbose_name='All Product Types?')),
            ],
            options={
                'verbose_name': 'Allowed Product Type Rule',
                'verbose_name_plural': 'Allowed Product Type Rules',
            },
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='order_id',
            field=models.TextField(max_length=36, verbose_name='Order id'),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='allowed_products_types',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Coupons.AllowedProductTypesRule', verbose_name='Allowed product types rule'),
            preserve_default=False,
        ),
    ]
