# Generated by Django 2.2.8 on 2021-03-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIds',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='allowedentitiesrule',
            name='all_entities',
            field=models.BooleanField(default=True, verbose_name='All entities?'),
        ),
        migrations.AlterField(
            model_name='allowedentitiesrule',
            name='entities',
            field=models.ManyToManyField(blank=True, to='Coupons.AllowedIds', verbose_name='Entities'),
        ),
        migrations.AlterField(
            model_name='allowedusersrule',
            name='all_users',
            field=models.BooleanField(default=True, verbose_name='All users?'),
        ),
        migrations.CreateModel(
            name='AllowedProductsRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_products', models.BooleanField(default=True, verbose_name='All Products?')),
                ('products', models.ManyToManyField(blank=True, to='Coupons.AllowedIds', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Allowed Product Rule',
                'verbose_name_plural': 'Allowed Product Rules',
            },
        ),
        migrations.AddField(
            model_name='ruleset',
            name='allowed_products',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Coupons.AllowedProductsRule', verbose_name='Allowed products rule'),
            preserve_default=False,
        ),
    ]
