# Generated by Django 2.2.8 on 2021-05-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0002_auto_20210515_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruleset',
            old_name='allowed_products_types',
            new_name='allowed_product_types',
        ),
    ]
