# Generated by Django 2.2.8 on 2021-03-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0003_auto_20210307_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validityrule',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='validityrule',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='validityrule',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Start date'),
        ),
    ]
