# Generated by Django 2.2.8 on 2021-03-09 21:46

import Coupons.helpers
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Coupons', '0005_auto_20210309_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=Coupons.helpers.get_random_code, max_length=15, verbose_name='Coupon Code')),
                ('times_used', models.IntegerField(default=0, editable=False, verbose_name='Times used')),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Created')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coupons.Discount')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coupons.Ruleset', verbose_name='Ruleset')),
            ],
        ),
    ]
