# Generated by Django 2.2.8 on 2021-03-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0006_couponhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='terms_and_conditions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='couponhistory',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='couponhistory',
            name='terms_and_conditions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='couponhistory',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='allowedentitiesrule',
            name='entities',
        ),
        migrations.AddField(
            model_name='allowedentitiesrule',
            name='entities',
            field=models.TextField(blank=True, null=True, verbose_name='Entities'),
        ),
        migrations.RemoveField(
            model_name='allowedproductsrule',
            name='products',
        ),
        migrations.AddField(
            model_name='allowedproductsrule',
            name='products',
            field=models.TextField(blank=True, null=True, verbose_name='Products'),
        ),
        migrations.RemoveField(
            model_name='allowedusersrule',
            name='users',
        ),
        migrations.AddField(
            model_name='allowedusersrule',
            name='users',
            field=models.TextField(blank=True, null=True, verbose_name='Users'),
        ),
        migrations.DeleteModel(
            name='AllowedIds',
        ),
    ]
