# Generated by Django 2.2.8 on 2021-04-30 13:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=36)),
                ('entity_type', models.CharField(choices=[('HOTELS', 'HOTELS'), ('TRANSPORT', 'TRANSPORT'), ('RENTALS', 'RENTALS'), ('RESORTS', 'RESORTS'), ('EVENTS', 'EVENTS')], default='HOTELS', max_length=30)),
                ('product_id', models.CharField(max_length=36)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
