# Generated by Django 2.2.8 on 2021-05-03 23:42

import WishList.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.CharField(default=WishList.models.get_id, max_length=36, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(max_length=36)),
                ('entity_type', models.CharField(choices=[('HOTELS', 'HOTELS'), ('TRANSPORT', 'TRANSPORT'), ('RENTALS', 'RENTALS'), ('RESORTS', 'RESORTS'), ('EVENTS', 'EVENTS')], default='HOTELS', max_length=30)),
                ('product_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
