# Generated by Django 3.2.4 on 2021-07-02 12:48

import WishList.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.CharField(default=WishList.models.get_id, max_length=36, primary_key=True, serialize=False)),
                ('related_id', models.CharField(max_length=36)),
                ('entity_type', models.CharField(blank=True, choices=[('STAY', 'STAY'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('EVENT', 'EVENT')], max_length=30, null=True)),
                ('entity_sub_type', models.CharField(blank=True, choices=[('HOTEL', 'HOTEL'), ('RESORT', 'RESORT'), ('GUESTHOUSE', 'GUESTHOUSE'), ('DORMITORY_MEN', 'DORMITORY_MEN'), ('DORMITORY_WOMEN', 'DORMITORY_WOMEN'), ('DORMITORY_ALL', 'DORMITORY_ALL'), ('PG_MEN', 'PG_MEN'), ('PG_WOMEN', 'PG_WOMEN'), ('PG_ALL', 'PG_ALL')], max_length=30, null=True)),
                ('item_type', models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('ENTITY', 'ENTITY'), ('PLACE', 'PLACE')], max_length=30)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
