# Generated by Django 2.2.8 on 2021-05-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WishList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='created_by',
        ),
    ]
