# Generated by Django 2.2.8 on 2021-05-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishList', '0003_auto_20210525_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='item_type',
            field=models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('ENTITY', 'ENTITY')], default='PRODUCT', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
