# Generated by Django 2.2.8 on 2021-06-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishList', '0005_wishlist_entity_sub_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='entity_id',
            new_name='related_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='entity_type',
            field=models.CharField(choices=[('STAY', 'STAY'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('EVENT', 'EVENT'), ('HIRE_A_VEHICLE', 'HIRE_A_VEHICLE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='item_type',
            field=models.CharField(choices=[('PRODUCT', 'PRODUCT'), ('ENTITY', 'ENTITY'), ('PLACE', 'PLACE')], max_length=30),
        ),
    ]
