# Generated by Django 2.2.8 on 2021-06-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WishList', '0006_auto_20210613_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('STAY', 'STAY'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('EVENT', 'EVENT'), ('HIRE_A_VEHICLE', 'HIRE_A_VEHICLE')], max_length=30, null=True),
        ),
    ]
