# Generated by Django 2.2.8 on 2021-04-25 22:37

import Payments.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.CharField(default=Payments.models.get_id, max_length=36, primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=36)),
                ('transaction_id', models.CharField(max_length=50)),
                ('utr', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('UPI', 'UPI'), ('COD', 'COD'), ('CARD', 'CARD')], default='UPI', max_length=10)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime.now)),
                ('entity_id', models.CharField(max_length=36)),
                ('total_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('entity_type', models.CharField(choices=[('HOTELS', 'HOTELS'), ('TRANSPORT', 'TRANSPORT'), ('RENTALS', 'RENTALS'), ('RESORTS', 'RESORTS'), ('EVENTS', 'EVENTS')], default='HOTELS', max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE')], default='PENDING', max_length=30)),
                ('booking_date', models.DateTimeField()),
            ],
            options={
                'unique_together': {('booking_id', 'booking_id')},
            },
        ),
    ]
