# Generated by Django 2.2.8 on 2021-04-23 00:10

import Payments.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.CharField(default=Payments.models.getId, max_length=36, primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=36)),
                ('transaction_id', models.CharField(max_length=50)),
                ('utr', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('UPI', 'UPI'), ('COD', 'COD'), ('CARD', 'CARD')], default='UPI', max_length=10)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
