# Generated by Django 2.2.8 on 2021-05-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtransaction',
            name='entity_type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('RESORT', 'RESORT'), ('EVENT', 'EVENT')], max_length=30),
        ),
        migrations.AlterField(
            model_name='refundtransaction',
            name='entity_type',
            field=models.CharField(choices=[('HOTEL', 'HOTEL'), ('TRANSPORT', 'TRANSPORT'), ('RENTAL', 'RENTAL'), ('RESORT', 'RESORT'), ('EVENT', 'EVENT')], max_length=30),
        ),
    ]
