# Generated by Django 2.2.8 on 2021-04-25 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='entity_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='total_money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterUniqueTogether(
            name='transactiondetails',
            unique_together={('booking_id', 'booking_id')},
        ),
    ]
