# Generated by Django 2.2.8 on 2021-05-01 13:35

import Payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTransaction',
            fields=[
                ('id', models.CharField(default=Payments.models.get_id, max_length=36, primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=36)),
                ('entity_id', models.CharField(max_length=36)),
                ('entity_type', models.CharField(choices=[('HOTELS', 'HOTELS'), ('TRANSPORT', 'TRANSPORT'), ('RENTALS', 'RENTALS'), ('RESORTS', 'RESORTS'), ('EVENTS', 'EVENTS')], max_length=30)),
                ('total_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('booking_date', models.DateTimeField()),
                ('booking_start', models.DateTimeField()),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('utr', models.CharField(blank=True, max_length=50, null=True)),
                ('mode', models.CharField(choices=[('NOT_DONE', 'NOT_DONE'), ('UPI', 'UPI'), ('COD', 'COD'), ('CARD', 'CARD')], default='NOT_DONE', max_length=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=30)),
                ('paid_to', models.CharField(choices=[('ENTITY', 'ENTITY'), ('MYC', 'MYC'), ('CUSTOMER', 'CUSTOMER')], default='MYC', max_length=30)),
                ('paid_by', models.CharField(choices=[('ENTITY', 'ENTITY'), ('MYC', 'MYC'), ('CUSTOMER', 'CUSTOMER')], default='MYC', max_length=30)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('booking_id', 'paid_to')},
            },
        ),
        migrations.DeleteModel(
            name='TransactionDetails',
        ),
    ]
