# Generated by Django 3.2.4 on 2021-10-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransaction',
            name='razorpay_order_id',
            field=models.CharField(default=123, max_length=36),
            preserve_default=False,
        ),
    ]
