# Generated by Django 2.2.8 on 2021-06-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingtransaction',
            unique_together=set(),
        ),
    ]
