# Generated by Django 2.2.8 on 2021-05-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_auto_20210506_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingtransaction',
            unique_together={('booking_id', 'paid_to', 'paid_by')},
        ),
        migrations.RemoveField(
            model_name='bookingtransaction',
            name='total_net_value',
        ),
    ]
