# Generated by Django 2.2.8 on 2021-05-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_auto_20210501_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtransaction',
            name='paid_to',
            field=models.CharField(choices=[('ENTITY', 'ENTITY'), ('MYC', 'MYC'), ('CUSTOMER', 'CUSTOMER')], default='ENTITY', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='bookingtransaction',
            unique_together={('booking_id', 'paid_to', 'paid_by')},
        ),
    ]
