# Generated by Django 2.2.8 on 2021-04-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_auto_20210425_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='entity_type',
            field=models.CharField(choices=[('HOTELS', 'HOTELS'), ('TRANSPORT', 'TRANSPORT'), ('RENTALS', 'RENTALS'), ('RESORTS', 'RESORTS'), ('EVENTS', 'EVENTS')], default='HOTELS', max_length=30),
        ),
    ]
