# Generated by Django 3.2.4 on 2021-10-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_bookingtransaction_razorpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=36)),
                ('razorpay_order_id', models.CharField(max_length=36)),
                ('razorpay_signature', models.CharField(max_length=200)),
            ],
        ),
    ]
