# Generated by Django 3.2.4 on 2021-10-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_alter_bookingtransaction_transaction_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=36)),
                ('razorpay_order_id', models.CharField(max_length=36)),
                ('razorpay_signature', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='razorpay_order_id',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingtransaction',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED'), ('FAILED', 'FAILED')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='refundtransaction',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED'), ('FAILED', 'FAILED')], default='PENDING', max_length=30),
        ),
    ]
