# Generated by Django 2.2.8 on 2021-04-25 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_transactiondetails_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
