# Generated by Django 2.2.8 on 2021-05-08 23:24

import Payments.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payments', '0003_auto_20210507_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='credited_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Payments.helpers.image_upload_to_transaction_proof),
        ),
    ]
