# Generated by Django 2.2.8 on 2021-05-02 13:52

import Payments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payments', '0003_auto_20210501_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookingtransaction',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='RefundTransaction',
            fields=[
                ('id', models.CharField(default=Payments.models.get_id, max_length=36, primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=36)),
                ('entity_id', models.CharField(max_length=36)),
                ('entity_type', models.CharField(choices=[('HOTELS', 'HOTELS'), ('TRANSPORT', 'TRANSPORT'), ('RENTALS', 'RENTALS'), ('RESORTS', 'RESORTS'), ('EVENTS', 'EVENTS')], max_length=30)),
                ('booking_date', models.DateTimeField()),
                ('booking_start', models.DateTimeField()),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('refund_reason', models.TextField()),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('utr', models.CharField(blank=True, max_length=50, null=True)),
                ('mode', models.CharField(choices=[('NOT_DONE', 'NOT_DONE'), ('UPI', 'UPI'), ('COD', 'COD'), ('CARD', 'CARD')], default='NOT_DONE', max_length=10)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
