# Generated by Django 2.2.8 on 2021-05-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_auto_20210508_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtransaction',
            old_name='image',
            new_name='transaction_proof',
        ),
    ]
