# Generated by Django 2.2.8 on 2021-03-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentalCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentbooking',
            unique_together={('booking_id', 'product_id')},
        ),
    ]
