# Generated by Django 2.2.8 on 2021-03-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentalCalendar', '0002_auto_20210304_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentbooking',
            name='is_cancelled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
