# Generated by Django 2.2.8 on 2021-03-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentalCalendar', '0003_rentbooking_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbooking',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
