# Generated by Django 3.2.4 on 2021-09-25 04:35

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchangecode',
            name='expiry_time',
            field=models.DateTimeField(default=authentication.models.get_expiry_time),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='expiry_time',
            field=models.DateTimeField(default=authentication.models.get_expiry_time),
        ),
        migrations.AddField(
            model_name='signupcode',
            name='expiry_time',
            field=models.DateTimeField(default=authentication.models.get_expiry_time),
        ),
    ]
