# Generated by Django 2.2.8 on 2021-02-28 10:06

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.TextField(default=authentication.models.random_string, max_length=6),
        ),
    ]
