# Generated by Django 2.2.8 on 2021-03-27 19:05

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='expiry_time',
            field=models.DateTimeField(default=authentication.models.getExpiryTime),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.TextField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
