# Generated by Django 3.2.4 on 2021-09-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210925_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
