# Generated by Django 2.2.8 on 2021-03-28 10:44

import authentication.validations
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210327_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10), authentication.validations.validate_phone], verbose_name='phone_number'),
        ),
    ]
