# Generated by Django 3.2.4 on 2021-09-26 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_rename_phone_otpcode_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(default='f9e65163-97c2-406f-8d1f-f8b918df4359', on_delete=django.db.models.deletion.CASCADE, to='UserApp.myuser'),
            preserve_default=False,
        ),
    ]
