# Generated by Django 2.2.8 on 2021-03-01 04:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210228_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 4, 51, 36, 857354, tzinfo=utc)),
        ),
    ]
