# Generated by Django 2.2.8 on 2021-03-01 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210301_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.TextField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 5, 11, 48, 841871, tzinfo=utc)),
        ),
    ]
