# Generated by Django 2.2.8 on 2021-03-01 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210301_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 10, 47, 10, 32192)),
        ),
    ]
