# Generated by Django 2.2.8 on 2021-03-23 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210301_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 18, 42, 24, 925216)),
        ),
    ]
